### ISSUE TITLE
Error formatting file: NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by Fogapod** [lexicalunit/atom-isort#23]
```python
Traceback (most recent call last):
  File "/home/eugene/.atom/packages/atom-isort/src/isort-wrapper.py", line 117, in <module>
    IsortTools().read_and_process()
  File "/home/eugene/.atom/packages/atom-isort/src/isort-wrapper.py", line 112, in read_and_process
    self._process_request(data)
  File "/home/eugene/.atom/packages/atom-isort/src/isort-wrapper.py", line 87, in _process_request
    correctly_sorted = (unicode(new_contents, 'utf-8') == request['file_contents'])
NameError: name 'unicode' is not defined
```

Related to #22 

```
$ python --version
Python 3.7.4
```

```
$ pip show isort
Name: isort
Version: 4.3.21
Summary: A Python utility / library to sort Python imports.
Home-page: https://github.com/timothycrosley/isort
Author: Timothy Crosley
Author-email: timothy.crosley@gmail.com
License: MIT
Location: /home/eugene/.local/lib/python3.7/site-packages
Requires: 
Required-by: pylint
```

**Comment by lexicalunit** [comment]
Sorry about that. A recent PR added support for unicode + Python 2 and broke support for Python 3. `v2.6.5` should resolve the issue.
